services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=adaptaki
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # redis:
  #   image: redis:6
  #   ports:
  #     - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      # - redis

  # celery:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   command: celery -A config worker -l info
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - backend
  #     - redis

  # celery-beat:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   command: celery -A config beat -l info
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - backend
  #     - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start
  
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./backend/media:/app/media
  #   depends_on:
  #     - backend
  #     - frontend