# Generated by Django 3.2.25 on 2024-11-27 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название узла')),
                ('description', models.TextField(verbose_name='Комментарий методиста')),
                ('node_type', models.CharField(choices=[('KN', 'Понятие (знаю)'), ('UN', 'Закономерность (понимаю)'), ('CS', 'Кейс (наблюдаю)'), ('SK', 'Навык (умею)')], max_length=2, verbose_name='тип узла')),
            ],
            options={
                'verbose_name': 'вершина графа',
                'verbose_name_plural': 'вершины графа',
            },
        ),
        migrations.CreateModel(
            name='NodeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_node', to='graph.graphnode', verbose_name='...к вершине')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_node', to='graph.graphnode', verbose_name='От вершины...')),
            ],
            options={
                'verbose_name': 'ребро в графе',
                'verbose_name_plural': 'ребра в графе',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
