# Generated by Django 3.2.25 on 2024-11-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20241127_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphnode',
            name='testability',
            field=models.BooleanField(default=True, verbose_name='Проверяемая?'),
        ),
    ]
