# Generated by Django 5.0.6 on 2024-05-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_concept_node_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.concept'),
        ),
    ]
