# Generated by Django 3.2.25 on 2024-11-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='graph_nodes',
            field=models.ManyToManyField(blank=True, related_name='questions', to='graph.GraphNode', verbose_name='привязан к вершинам графа:'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('string', 'Обычная проверка строки'), ('numeric', 'Проверка числа'), ('ordered_set', 'Набор символов в строгом порядке'), ('unordered_set', 'Набор символов в случайном порядке'), ('single_choice', 'Выбор одного верного ответа'), ('multiple_choice', 'Выбор нескольких верных ответов')], max_length=50, verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tolerance',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='допустимая погрешность (для численного ответа)'),
        ),
    ]
