# Generated by Django 3.2.25 on 2024-11-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodics', '0003_rename_subject_concept_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='subjects',
        ),
        migrations.AddField(
            model_name='concept',
            name='subjects',
            field=models.ManyToManyField(default=None, null=True, related_name='concepts', to='methodics.Subject', verbose_name='Предметы'),
        ),
    ]
