# Generated by Django 3.2.25 on 2024-11-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodics', '0004_auto_20241127_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFromTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название класса')),
                ('class_number', models.PositiveIntegerField(unique=True, verbose_name='Номер класса')),
                ('description', models.TextField(null=True, verbose_name='Комментарий методиста')),
            ],
            options={
                'verbose_name': 'класс',
                'verbose_name_plural': 'классы',
                'ordering': ['class_number'],
            },
        ),
    ]
