# Generated by Django 3.2.25 on 2024-11-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodics', '0005_classfromtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfromtag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий методиста'),
        ),
    ]
